services:
    postgres:
        image: postgres:18.1
        container_name: postgres18
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            TZ: America/Chicago
        ports:
            - "5432:5432"
        volumes:
            - ./pg_database:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
            interval: 10s
            timeout: 5s
            retries: 5
